language: android
jdk: oraclejdk8
sudo: required
dist: precise
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
licenses:
  - android-sdk-preview-license-c81a61d9
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
  - ./gradlew assembleRelease --stacktrace --no-daemon
after_script:
  - ./gradlew crashlyticsUploadDistributionRelease
before_install:
  - chmod +x gradlew
branches:
  only:
  - master